### ISSUE TITLE
Similar Paper

### ISSUE THREAD

**Issue by sunstarchan** [Zengyi-Qin/Weakly-Supervised-3D-Object-Detection#2]
I read another paper with almost the same name
**Weakly Supervised 3D Object Detection from Lidar Point Cloud**
https://arxiv.org/pdf/2007.11901.pdf

Could you explain more about the difference?

**Comment by Zengyi-Qin** [comment]
There are two major differences:

1. The targeted problem is different.
 -Though the titles are very similar (weakly supervised ...), their work is more "semi-supervised" and our work is more "unsupervised". This is because, their method still requires 3D bbox annotations (while the number of annotations is smaller than fully supervised methods). Our method does not require annotated 3D bbox at all. Our object proposal stage is completely unsupervised.

2. The methodology is significantly different.
-In the two-stage detection framework:
In the first stage, we propose the UPM (unsupervised 3D object proposal module) that generates object proposals using Normalized Point Cloud Densities. Their method uses limited annotation to learn cylinder object proposals.
In the second stage, we propose the cross-model knowledge distillation scheme that transfers the knowledge from off-the-shelf image datasets to the point cloud domain to enable the learning of 3D object detection from point clouds. Their method learns to refine the proposals from the limited annotations.

**Comment by sunstarchan** [comment]
Thanks for your quickly reply. I went through these two papers. Your idea is kind of understandable by using UPM and images. But theirs is mainly focus another point as you mentioned above.
